//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace intStore.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Shipment()
        {
            this.Goods = new HashSet<Goods>();
        }
    
        public int id_Shipment { get; set; }
        public Nullable<int> id_Supplier { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> id_StatuShipment { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<decimal> Cost { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Goods> Goods { get; set; }
        public virtual StatusShipment StatusShipment { get; set; }
        public virtual Suppliers Suppliers { get; set; }
    }
}
