//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace intStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goods
    {
        public int id_Product { get; set; }
        public string NameProduct { get; set; }
        public string Description { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<System.DateTime> DateProduct { get; set; }
        public string ImageProduct { get; set; }
        public Nullable<int> id_Shipment { get; set; }
    
        public virtual Shipment Shipment { get; set; }
    }
}
