//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace intStore
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InternetStoreEntities1 : DbContext
    {
        private static InternetStoreEntities1 _context;
        public static InternetStoreEntities1 GetContext()
        {
            if(_context == null)
                _context = new InternetStoreEntities1();
            return _context;
        }
        public InternetStoreEntities1()
            : base("name=InternetStoreEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Goods> Goods { get; set; }
        public virtual DbSet<Shipment> Shipment { get; set; }
        public virtual DbSet<Suppliers> Suppliers { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
