//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace intStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int id_Order { get; set; }
        public Nullable<int> id_Customer { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<int> id_StatusOrders { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<int> id_Payments { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual Payments Payments { get; set; }
        public virtual StatuOrders StatuOrders { get; set; }
    }
}
